server:
  port: 6001

spring:
  datasource:
    url: jdbc:postgresql://172.30.1.94:5432/gather
    username: distributed
    password: qwer1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    database: postgresql
